---
- name: Enable ipv4 forwarding
  copy:
    src: gateway.conf
    dest: /usr/lib/sysctl.d/gateway.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - sysctl
  tags: gateway

- name: Install gateway firewall rules
  template:
    src: gateway.conf.j2
    dest: /etc/ferm.d/gateway.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - ferm
  tags: gateway
