---
- name: Configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  notify:
    - hostname
  tags: hostname

- name: Configure hostname file
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  notify:
    - hostname
  tags: hostname
