---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible
  - pip install yamllint
  - ansible --version

script:
  - ./tests/check.sh
