---
- name: Install iptables
  xbps: pkg=iptables state=present
  tags: iptables

- name: Install iptables-reload
  copy: src=iptables-reload dest=/usr/local/sbin/iptables-reload owner=root group=root mode=0755
  tags: iptables

- name: Add dhcpcd iptables hook
  copy: src=99-iptables dest=/usr/share/dhcpcd/hooks/99-iptables owner=root group=root mode=0740
  notify:
    - dhcpcd
  tags:
    - iptables
    - dhcpcd

- name: Enable dhcpcd iptables hook
  file: src=/usr/share/dhcpcd/hooks/99-iptables dest=/usr/libexec/dhcpcd-hooks/99-iptables state=link
  notify:
    - dhcpcd
  tags:
    - iptables
    - dhcpcd

- name: Make iptables.d
  file: path=/etc/iptables.d state=directory owner=root group=root mode=0755
  tags: iptables

- name: Configure iptables base rules
  template: src=0common.rules.j2 dest=/etc/iptables.d/0common.rules owner=root group=root mode=0644
  notify:
    - iptables
  tags: iptables

- name: Configure xbps iptables rules
  template: src=xbps.rules.j2 dest=/etc/iptables.d/xbps.rules owner=root group=root mode=0644
  notify:
    - iptables
  tags:
    - iptables
    - xbps

- name: Make ip6tables.d
  file: path=/etc/ip6tables.d state=directory owner=root group=root mode=0755
  tags: iptables

- name: Configure iptables6 base rules
  copy: src=0common.6rules dest=/etc/ip6tables.d/0common.6rules owner=root group=root mode=0644
  notify:
    - iptables
  tags: iptables
