---
- name: Configure dhcpcd
  template: src=dhcpcd.conf.j2 dest=/etc/dhcpcd.conf owner=root group=root mode=0644
  notify:
    - dhcpcd
  tags: dhcpcd

- name: Enable dhcpcd
  file: src=/etc/sv/dhcpcd dest=/var/service/dhcpcd state=link
  tags: dhcpcd
