---
- name: Add users
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.password | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
    groups: "{{ item.value.groups | default(omit) }}"
    append: "{{ item.value.append  | default(omit) }}"
  with_dict: "{{ users }}"
  loop_control:
    label: "{{ item.key }}"
  tags:
    - addusers
    - vault

- name: Add ssh keys
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value.pub_key }}"
  when: "{{ item.value.pub_key is defined }}"
  with_dict: "{{ users }}"
  loop_control:
    label: "{{ item.key }}"
  tags: addusers
