---
dependencies: []
galaxy_info:
    author: kulinacs
    company: APE Labs
    description: Configures sshd
    galaxy_tags:
      - sshd
    license: ISC
    min_ansible_version: 1.2
    platforms:
      - name: Void Linux
        versions:
          - any
      - name: OpenBSD
        versions:
          - 6.0
