---
dependencies: []
galaxy_info:
    author: kulinacs
    company: APE Labs
    description: Configures doas
    galaxy_tags:
      - doas
    license: ISC
    min_ansible_version: 1.2
    platforms:
      - name: OpenBSD
        versions:
          - 6.0
