---
- name: Configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: "/usr/sbin/sshd -f %s -t"
  when: ansible_distribution != "OpenBSD"
  notify: sshd
  tags: sshd

- name: Configure sshd (OpenBSD)
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: 0644
    validate: "/usr/sbin/sshd -f %s -t"
  when: ansible_distribution == "OpenBSD"
  notify: obsd_sshd
  tags: sshd
